name: agrostack
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.10

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.1.3
  intl: ^0.17.0

  firebase_auth: ^4.1.3
  firebase_core: ^2.3.0
  dartz: ^0.10.1
  dio: ^4.0.6
  pretty_dio_logger: ^1.2.0-beta-1
  google_sign_in: ^5.4.4
  # google_maps_flutter: ^2.2.3
  cached_network_image: ^3.2.3
  google_maps_flutter: ^2.2.3
  location: ^4.4.0
  custom_info_window: ^1.0.1


dev_dependencies:
  bloc_test: ^9.1.0
  build_runner_core: ^7.2.7
  flutter_test:
    sdk: flutter
  freezed: ^2.2.0
  mocktail: ^0.3.0
  build_runner:
  very_good_analysis: ^3.1.0
  flutter_launcher_icons: ^0.11.0



flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/


flutter_icons:
  android: true
  ios: false
  image_path: "assets/images/laucher.png"